### ISSUE TITLE
No longer works with Mongo Atlas

### ISSUE THREAD

**Issue by jorourke** [honeycombio/atlas#2]
It seems this no longer works with mongo atlas as the API must have changed, see: https://docs.atlas.mongodb.com/reference/api/pa-get-slow-query-logs/

Basically, it seems to get some logs, but not the slow query logs. Could use updating

**Comment by MikeGoldsmith** [comment]
Hey @jorourke - thanks for creating the issue.

This project seems to be fairly out of date. We'll add this to our backlog to decide on next steps.

**Comment by vreynolds** [comment]
- #12
